EcomForms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('siteadmin/',include('adminpanel.urls')),
    path('',include('sitevisitor.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitevisitor/urls.py
from django.urls import path
from .views import home,register_user,user_login, user_home

app_name = 'sitevisitor'
urlpatterns=[
    path('',home, name= 'home'),
    path('sign_up/', register_user, name = 'sign_up'),
    path('sign_in/',user_login, name='sign_in'),
    path('user_home/',user_home, name='user_home'),



]

sitevisitor/models.py
from django.db import models

sitevisitor/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class Registration_Form(UserCreationForm):
    
    email = forms.EmailField(
        required=True,
        label="Email Address",
        widget=forms.EmailInput(attrs={'class': 'form-control'})
    )
    first_name = forms.CharField(
        max_length=30,
        required=True,
        label="First Name",
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    last_name = forms.CharField(
        max_length=30,
        required=True,
        label="Last Name",
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    username = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        label="Username"
    )
    password1 = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        label="Password"
    )
    password2 = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        label="Confirm Password"
    )
    class Meta:
        model = User
        fields = ['first_name','last_name','email','username','password1','password2']

class Login_Form(forms.Form):
    username = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        label="Username"
    )
    password1 = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        label="Password"
    )

sitevisitor/views.py
from django.shortcuts import render,redirect
from adminpanel.models import Product
from .forms import Registration_Form, Login_Form
from django.contrib import messages
from django.contrib.auth import authenticate,login

# Create your views here.
def home(request):
    products = Product.objects.all().order_by('-id')     
    return render(request,'sitevisitor/home.html',{'products':products})

def register_user(request):
    if request.method == 'POST':
        form = Registration_Form(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'User Registered successfully!!!')
            return redirect('sitevisitor:home')
    else:
        form = Registration_Form()
    context={
        'form':form
    }
    return render(request, 'sitevisitor/register.html',context)

def user_login(request):
    
    if request.method =='POST':
        form = Login_Form(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                if user.is_staff:
                    return redirect('adminpanel:home')
                else:
                    return redirect('sitevisitor:user_home')
    else:
        form = Login_Form()
    context ={
        'form':form
    }
    return render(request,'sitevisitor/login.html',context)

def user_home(request):
    logged_user = request.user
    context={
        'user':logged_user
    }
    return render(request,'sitevisitor/user_home.html',context)

templates/sitevisitor/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar bg-primary border-bottom border-body">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Shopify</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'sitevisitor:home'%}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'sitevisitor:sign_up'%}">Register</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'sitevisitor:sign_in'%}">Login</a>
              </li>
              
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
    {% if messages %}
        {% for message in messages %}
            <script>
                alert('{{ message }}')
            </script>
        {% endfor %}
    {% endif %}
    {% block content %}{% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
</body>
</html>

templates/sitevisitor/home.html
{% extends 'sitevisitor/base.html' %}
{% block title %}
Shopify | Home
{% endblock %}
    
{% block content %}

<div class="row m-3">
  {% if products %}
    {% for product in products %}
    <div class="col-3 col-lg-3 col-md-3 col-sm-3">
      <div class="card" style="width: 18rem;">
        <img src="{{ product.product_image.url }}" class="card-img-top" alt="{{product.name}}" height="200px">
        <div class="card-body">
          <h5 class="card-title">{{product.name}}</h5>
          <p class="card-text">{{product.description }}</p>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">$ {{product.price }}</li>
          <li class="list-group-item">
            {% if product.stock > 5 %}
                <p class="text-primary">Currently Available</p>
            {% elif product.stock > 0 and product.stock < 5 %}
                <p class="text-warning">Only {{product.stock }} left!!</p>
            {% else %}
                <p class="text-danger">Currently Unvailable!!!</p>
            {% endif %}
          </li>
          
        </ul>
        
      </div>
    </div>
    {% endfor %}
  {% else %}
  {% endif %}
</div>



{% endblock %}

templates/sitevisitor/login.html
{% extends 'sitevisitor/base.html' %}
{% block title %}
Shopify | Home
{% endblock %}
    
{% block content %}
<div class="row m-3">
  <h1> User Login</h1>
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="#">Home</a></li>
      <li class="breadcrumb-item active" aria-current="page">User Login</li>
    </ol>
  </nav>
    <form method="post" class="m-3">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class = "btn btn-primary">Login</button>
    
    </form>
</div>
{% endblock %}

templates/sitevisitor/register.html
{% extends 'sitevisitor/base.html' %}
{% block title %}
Shopify | Home
{% endblock %}
    
{% block content %}
<div class="row m-3">
  <h1> Register User</h1>
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="#">Home</a></li>
      <li class="breadcrumb-item active" aria-current="page">Register User</li>
    </ol>
  </nav>
    <form method="post" class="m-3">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class = "btn btn-primary">Save Details</button>
    
    </form>
</div>
{% endblock %}

templates/sitevisitor/user_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar bg-success border-bottom border-body">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Shopify</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'sitevisitor:home'%}">Home</a>
              </li>
              
              
            </ul>
            
          </div>
        </div>
      </nav>
    {% if messages %}
        {% for message in messages %}
            <script>
                alert('{{ message }}')
            </script>
        {% endfor %}
    {% endif %}
    {% block content %}{% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
</body>
</html>

templates/sitevisitor/user_home.html
{% extends 'sitevisitor/user_base.html' %}
{% block title %}
Shopify | Home
{% endblock %}
    
{% block content %}
<div class="row m-3">
  <h1> User Home</h1>
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="#">Home</a></li>
      <li class="breadcrumb-item active" aria-current="page">User Home</li>
    </ol>
  </nav>
    <h1>{{ user.first_name }}&nbsp;{{ user.last_name}}</h1>
</div>
{% endblock %}