EcomForms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('siteadmin/',include('adminpanel.urls')),
    path('',include('sitevisitor.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminpanel/urls.py
from django.urls import path
from .views import (home, category_list, edit_category, delete_category, add_product,
                    edit_product,delete_product,sign_out)

app_name = 'adminpanel'
urlpatterns = [
    path('', home, name ='home'),
    path('category_list/', category_list, name ='category_list'),
    path('edit_category/<int:category_id>/', edit_category, name = 'edit_category'),
    path('delete_category/<int:category_id>/', delete_category, name = 'delete_category'),
    path('add_product/<int:category_id>/', add_product, name = 'add_product'),
    path('edit_product/<int:product_id>/', edit_product, name = 'edit_product'),
    path('delete_product/<int:product_id>/', delete_product, name = 'delete_product'),
    path('logout/',sign_out,name='sign_out')

]

adminpanel/models.py
from django.db import models



# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    product_image = models.ImageField(upload_to='products/')
    price = models.DecimalField(max_digits=10,decimal_places=2)
    stock  = models.IntegerField()
    category = models.ForeignKey(Category,on_delete=models.CASCADE)

    def __str__(self):
        return self.name

adminpanel/forms.py
from django import forms
from .models import Category, Product

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control','placeholder':'Enter Category'})
        }
        

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ['category']
        widgets = {
            'name':forms.TextInput(attrs={'class':'form-control','placeholder':'Name of Product'}),
            'description':forms.Textarea(attrs={'class':'form-control','placeholder':'Description'}),
            'product_image':forms.ClearableFileInput(attrs={'class':'form-control'}),
            'price':forms.NumberInput(attrs={'class':'form-control','placeholder':'Enter Price'}),
            'stock':forms.NumberInput(attrs={'class':'form-control','placeholder':'Available Stock'}),
            
        }
        

adminpanel/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Category,Product
from .forms import CategoryForm, ProductForm
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url='/sign_in/')
def home(request):
     products = Product.objects.all().order_by('-id')
     return render(request,'adminpanel/home.html',{'products':products})

@login_required(login_url='/sign_in/')
def category_list(request):
    categories = Category.objects.all().order_by('-id')
    if request.method == "POST":
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'A new category is added')
            return redirect('adminpanel:category_list')
    else:
        form = CategoryForm()
    context = {
        'form':form,
        'categories':categories
    }
    return render(request,'adminpanel/category_list.html',context)

@login_required(login_url='/sign_in/')
def edit_category(request,category_id):
    category = get_object_or_404(Category, id = category_id)
    if request.method == 'POST':
        form = CategoryForm(request.POST,instance = category)
        if form.is_valid():
            form.save()
            messages.success(request,'Category is updated')
            return redirect('adminpanel:category_list')
    else:
        form = CategoryForm(instance = category)

    context ={
        'form':form
        
        }
    return render(request,'adminpanel/edit_category.html', context)

@login_required(login_url='/sign_in/')
def delete_category(request, category_id):
    category = get_object_or_404(Category, id = category_id)   
    category.delete()
    messages.success(request,'Category Deleted Successfully')
    return redirect('adminpanel:category_list')

@login_required(login_url='/sign_in/')  
def add_product(request, category_id):
    category = get_object_or_404(Category, id= category_id)
    request.session['category_id'] = category_id
    products = Product.objects.filter(category = category).order_by('-id')
    if request.method =='POST':
        form = ProductForm(request.POST,request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.category = category
            product.save()
            messages.success(request,'A new product is added')
            return redirect('adminpanel:add_product', category_id  = category_id)

    else:
        form = ProductForm()

    context ={
        'form':form,
        'products':products
    }
    return render(request,'adminpanel/add_product.html',context)

@login_required(login_url='/sign_in/')
def edit_product(request, product_id):
    category_id = request.session.get('category_id',0)    
    product = get_object_or_404(Product, id = product_id)
    if request.method == 'POST':
        form = ProductForm(request.POST,request.FILES, instance = product)
        if form.is_valid():
            form.save()
            messages.success(request,'Product is updated')
            return redirect('adminpanel:add_product', category_id  = category_id)
    else:
        form = ProductForm(instance = product)

    context ={
        'form':form
        
        }

    return render(request,'adminpanel/edit_products.html',context)

@login_required(login_url='/sign_in/')
def delete_product(request,product_id):
    category_id = request.session.get('category_id',0)
    product = get_object_or_404(Product, id = product_id)   
    product.delete()
    messages.success(request,'Product Deleted Successfully')
    return redirect('adminpanel:add_product', category_id  = category_id)

@login_required(login_url='/sign_in/')
def sign_out(request):
    logout(request)
    return redirect('sitevisitor:home')

templates/adminpanel/add_product.html
{% extends 'adminpanel/base.html' %}
{% block title %}
Shopify | Dashboard
{% endblock %}
    
{% block content %}
<div class="row m-3">
  <div class="col-lg-9 col-md-6 col-sm-6">
      <h1> Add Product</h1>
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="#">Home</a></li>
          <li class="breadcrumb-item active" aria-current="page">Add Products</li>
        </ol>
      </nav>
      <form method="post" class="m-3" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class = "btn btn-primary">Save Product</button>
    
      </form>
    </div>
</div>
<div class="row m-3">
  {% if products %}
    {% for product in products %}
    <div class="col-3 col-lg-3 col-md-3 col-sm-3">
      <div class="card" style="width: 18rem;">
        <img src="{{ product.product_image.url }}" class="card-img-top" alt="{{product.name}}" height="200px">
        <div class="card-body">
          <h5 class="card-title">{{product.name}}</h5>
          <p class="card-text">{{product.description }}</p>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">$ {{product.price }}</li>
          <li class="list-group-item">
            {% if product.stock > 5 %}
                <p class="text-primary">Currently Available</p>
            {% elif product.stock > 0 and product.stock < 5 %}
                <p class="text-warning">Only {{product.stock }} left!!</p>
            {% else %}
                <p class="text-danger">Currently Unvailable!!!</p>
            {% endif %}
          </li>
          
        </ul>
        <div class="card-body text-center">
          <a href="{% url 'adminpanel:edit_product' product.id %}" class="btn btn-warning">Edit</a>
          <a href="{% url 'adminpanel:delete_product' product.id %}" class="btn btn-danger" onclick="return confirm('Are you sure you want to Delete this Product?')">Delete</a>
        
         </div>
      </div>
    </div>
    {% endfor %}
  {% else %}
  {% endif %}
</div>
{% endblock %}

templates/adminpanel/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar bg-dark border-bottom border-body" data-bs-theme="dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Shopify</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'adminpanel:home'%}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'adminpanel:category_list'%}">Category</a>
              </li>
              
              <li class="nav-item">
                <a class="nav-link" href="{% url 'adminpanel:sign_out'%}">Logout</a>
              </li>
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
    {% if messages %}
        {% for message in messages %}
            <script>
                alert('{{ message }}')
            </script>
        {% endfor %}
    {% endif %}
    {% block content %}{% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
</body>
</html>

templates/adminpanel/category_list.html
{% extends 'adminpanel/base.html' %}
{% block title %}
Shopify | Dashboard
{% endblock %}
    
{% block content %}


<div class="row m-3">
    <div class="col-lg-9 col-md-6 col-sm-6">
    <h1> Add Category </h1>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          
          <li class="breadcrumb-item active" aria-current="page">Home</li>
        </ol>
      </nav>
    <form method="post" class="m-3">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class = "btn btn-primary">Save Category</button>

    </form>
    </div>
</div>
<div class="row m-3">
    <table class="table table-striped table-dark m-3 text-center w-75">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Category Name</th>
            <th scope="col" colspan="3">Actions</th>
            
        </tr>
        </thead>
        <tbody>
            {% if categories %}
                {% for category in categories %}
                    <tr>
                        <th scope="row">{{category.id}}</th>
                        <td>{{category.name}}</td>
                        <td><a href="{% url 'adminpanel:edit_category' category.id %}" class = "btn btn-warning">Edit</a></td>
                        <td><a href="{% url 'adminpanel:delete_category' category.id %}" class = "btn btn-danger" onclick="return confirm('Do you want to delete this category?')">Delete</a></td>
                        <td><a href="{% url 'adminpanel:add_product' category.id %}" class = "btn btn-success">Add Products</a></td>
                    </tr>
                {% endfor %}
            {% else %}
                    <tr><td colspan="5"><p>No records to display</p></td></tr>
            {% endif %}
        
        </tbody>
    </table>
</div>

{% endblock %}

templates/adminpanel/edit_category.html
{% extends 'adminpanel/base.html' %}
{% block title %}
Shopify | Dashboard
{% endblock %}
    
{% block content %}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="#">Home</a></li>
      <li class="breadcrumb-item active" aria-current="page">Edit Category</li>
    </ol>
  </nav>
  <div class="row m-3">
    <div class="col-lg-9 col-md-6 col-sm-6">

    <form method="post" class="m-3">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class = "btn btn-primary">Update Category</button>
    
    </form>
    </div>
</div>



{% endblock %}

templates/adminpanel/edit_products.html
{% extends 'adminpanel/base.html' %}
{% block title %}
Shopify | Dashboard
{% endblock %}
    
{% block content %}
<div class="row m-3">
  <div class="col-lg-9 col-md-6 col-sm-6">
  <h1> Edit Product</h1>
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="#">Home</a></li>
      <li class="breadcrumb-item"><a href="#">Add Product</a></li>
      <li class="breadcrumb-item active" aria-current="page">Edit Product</li>
    </ol>
  </nav>
    <form method="post" class="m-3" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class = "btn btn-primary">Update Product</button>
    
    </form>
    </div>
</div>



{% endblock %}

templates/adminpanel/home.html
{% extends 'adminpanel/base.html' %}
{% block title %}
Shopify | Dashboard
{% endblock %}
    
{% block content %}

<div class="row m-3">
  {% if products %}
    {% for product in products %}
    <div class="col-3 col-lg-3 col-md-3 col-sm-3">
      <div class="card" style="width: 18rem;">
        <img src="{{ product.product_image.url }}" class="card-img-top" alt="{{product.name}}" height="200px">
        <div class="card-body">
          <h5 class="card-title">{{product.name}}</h5>
          <p class="card-text">{{product.description }}</p>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">$ {{product.price }}</li>
          <li class="list-group-item">
            {% if product.stock > 5 %}
                <p class="text-primary">Currently Available</p>
            {% elif product.stock > 0 and product.stock < 5 %}
                <p class="text-warning">Only {{product.stock }} left!!</p>
            {% else %}
                <p class="text-danger">Currently Unvailable!!!</p>
            {% endif %}
          </li>
          
        </ul>
        
      </div>
    </div>
    {% endfor %}
  {% else %}
  {% endif %}
</div>



{% endblock %}